# Generated by Django 5.1.4 on 2025-01-13 15:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('min_delivery_time', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('revision', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)])),
                ('delivery_time_in_days', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('offer_type', models.CharField(choices=[('BASIC', 'basic'), ('STANDARD', 'standard'), ('PREMIUM', 'premium')], default='BASIC', max_length=20)),
                ('features', models.JSONField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='coderr_app.offer')),
            ],
        ),
    ]
