# Generated by Django 5.1.4 on 2025-01-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetail',
            old_name='revision',
            new_name='revisions',
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'BASIC'), ('standard', 'STANDARD'), ('premium', 'PREMIUM')], default='basic', max_length=20),
        ),
    ]
