# Generated by Django 5.1.4 on 2025-01-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0003_alter_offer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
    ]
