# Generated by Django 5.1.4 on 2025-01-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0004_remove_offer_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
