# Generated by Django 5.1.4 on 2025-01-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='coderr_app.offerdetail'),
            preserve_default=False,
        ),
    ]
