# Generated by Django 5.1.4 on 2025-01-22 14:50

from django.db import migrations
from shared.dummy_data import create_dummy_data


def load_initial_data(apps, schema_editor):
    create_dummy_data()


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0010_alter_review_rating'),
        ('user_auth_app', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
